apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: data-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: gryphon2411/derkino-data_service:latest
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: KAFKA_HOSTS
          value: kafka-controller-0.kafka-controller-headless.kafka-system.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka-system.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka-system.svc.cluster.local:9092
        - name: KAFKA_PASSWORD
          value: w43Pw4Q9cb
        - name: KAFKA_USERNAME
          value: root
        - name: MONGO_DATABASE
          value: derkino
        - name: MONGO_HOST_ADDRESS
          value: mongodb.mongodb-system
        - name: MONGO_HOST_PORT
          value: "27017"
        - name: MONGO_PASSWORD
          value: X6d9r2SgJ8xQgpGL
        - name: MONGO_USERNAME
          value: root
        - name: SERVICE_HOST_PREFIX
          value: /api/v1
