apiVersion: v1
kind: Secret
metadata:
  name: postgres-root-user-credentials
  namespace: postgres-system
type: Opaque
data:
  # echo -n postgres | base64
  username: cG9zdGdyZXM=
  # echo -n VCi6aCUFzU49J4aK3HX | base64
  password: VkNpNmFDVUZ6VTQ5SjRhSzNIWA==
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-system
spec:
  selector:
    app: postgres
  ports:
  - name: default
    port: 5432
    targetPort: 5432
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres-system
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - name: default
          containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-root-user-credentials
              key: password
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-initdb-volume
          mountPath: /docker-entrypoint-initdb.d/postgres-initdb.sh
          subPath: postgres-initdb.sh
      volumes:
      - name: postgres-initdb-volume
        configMap:
          name: postgres-initdb
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
