apiVersion: v1
kind: Service
metadata:
  name: trend-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: trend-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trend-service
  template:
    metadata:
      labels:
        app: trend-service
    spec:
      containers:
      - name: trend-service
        image: gryphon2411/derkino-trend_service:latest
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: KAFKA_HOSTS
          value: kafka-controller-0.kafka-controller-headless.kafka-system.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.kafka-system.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.kafka-system.svc.cluster.local:9092
        - name: KAFKA_PASSWORD
          value: w43Pw4Q9cb
        - name: KAFKA_USERNAME
          value: root
        - name: MONGO_DATABASE
          value: "derkino"
        - name: MONGO_HOST_ADDRESS
          value: "192.168.49.2"
        - name: MONGO_HOST_PORT
          value: "31413"
        - name: MONGO_PASSWORD
          value: "X6d9r2SgJ8xQgpGL"
        - name: MONGO_USERNAME
          value: "root"
        - name: SERVICE_HOST_PREFIX
          value: "/api/v1"
